version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: search_db_container
    environment:
      MYSQL_ROOT_PASSWORD: 'Yes@070514'
      MYSQL_DATABASE: 'search_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Yes@070514'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - '6379:6379'

  app:
    build:
      context: .
    container_name: symfony_app
    depends_on:
      - database
      - redis
    environment:
      DATABASE_URL: "mysql://root:Yes%40070514@database:3306/search_db?serverVersion=8.0.39&charset=utf8mb4"
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/html
    command: bash -c "composer install && php bin/console doctrine:database:create --if-not-exists && php-fpm"

volumes:
  db_data:
